---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        kube2iam.beta.domain.net/role: "arn:aws:iam::12345678901:role/testns/k8s/platform"
    spec:
      containers:
        - name: go
          image: 12345678901.dkr.ecr.us-west-2.amazonaws.com/chatbot:latest
          imagePullPolicy: Always
